### ISSUE TITLE
Integration with Supabase

### ISSUE THREAD

**Issue by soorya-u** [soorya-u/Code-Compass#7]
# Integration with Supabase

## TODO

- [ ] Use Supabase Storage to store Markdown Files
- [ ] Use Supabase Edge Functions Upload Markdown Files
- [ ] Use Supabase Database to Store Markdown Details
- [x] Use Supabase Auth for User Management
