### ISSUE TITLE
feat: Restructuring Repository

### ISSUE THREAD

**Issue by soorya-u** [soorya-u/Code-Compass#9]
# Restructuring Repository

##  TODO

- [x] Use Expo-Stack
- [x] Migrate Necessary Plugins and Config files
- [x] Fix Nativewind Issues
- [x] Add src Directory
